### ISSUE TITLE
The fields: size of the contribution and contribution per day are not nullable

### ISSUE THREAD

**Issue by RafaIG** [actionprojecteu/dmptool-generator#3]
Every field of the questionnaire can be left in blank and the dmp is still generated properly. However there are two exceptions of this the size of the contribution and contribution per day. In this case the files are not generated and the task status is set to "error". 

In addition, the dmptool-generator controls this error and prints it in the logs, so the docker does not get stopped:
![image](https://user-images.githubusercontent.com/55830012/75246438-0bbd7080-57d0-11ea-9b01-05c344ee6549.png)

**Comment by esgg** [comment]
It will be fixed when they are replaced by another field to represent the contribution of a project
